Feat/dev
JessicaDSL/todolist pull request #1
Opened 2022-02-01 20:39 UTC by JessicaDSL

2022-02-15 23:07 UTC, RonaldoSetzer requested changes

2022-02-15 23:07 UTC, RonaldoSetzer commented on src/Context/index.js
> +    setList([...list, { mainTask: task }]);
O objeto task deveria possuir id, title, description, status.
Para gerar ids voce pode utilizar `uuid`

```ts
const task = {
  id: string,
  title: string,
  description: string,
  status: string,
}
```

2022-02-15 23:07 UTC, RonaldoSetzer commented on src/Context/index.js
> +    const newList = list.filter((task) => task !== item);
Para remover utilize o ID
```suggestion
    setList(list.filter((task) => task.id !== id));
```

2022-02-15 23:07 UTC, RonaldoSetzer commented on src/Context/index.js
> +  const [list, setList] = useState([]);
```suggestion
  const [tasks, setTasks] = useState([]);
```

2022-02-15 23:07 UTC, RonaldoSetzer commented on src/components/AddQuickTodo/AddQuickTodo.js
> +          e.preventDefault();
Criar metod espefico para o click

2022-02-15 23:07 UTC, RonaldoSetzer commented on src/components/Header/Header.js
> +        <h1>Todo List</h1>
Crirar estilo Title ao invez de utlizar h1 puro

2022-02-15 23:07 UTC, RonaldoSetzer commented on src/components/Header/Header.js
> +      </p>
Os <p> sao desnecessarios

2022-02-21 21:43 UTC, JessicaDSL commented on src/Context/index.js
> +    setList([...list, { mainTask: task }]);
Ao criar as propriedades no objeto, ele já inicia automaticamente um objeto novo, dificultando a criação da lista.

2022-03-15 14:03 UTC, merged